### ISSUE TITLE
递归报错

### ISSUE THREAD

**Issue by epicchaos** [aimkiray/op-script#4]
尝试次数过多 出现RuntimeError: maximum recursion depth exceededhuo或者被进程被kill

**Comment by aimkiray** [comment]
惊了，咱这脚本居然能正常运行到最大递归深度限制的地步嘛~
最大递归深度限制是py为避免耗尽计算机内存而设置的，正常情况。
把递归改为循环试试，稍后更新 code
要不试试op日本

**Comment by epicchaos** [comment]
嗯哪 一直都在试香港的 开出来的都不能用 >﹏<
尝试执行更新后的脚本 能登陆 但卡在第一次尝试
2017-12-15 08:07:22,829: [INFO]  The 1st attempt...
Traceback (most recent call last):
  File "op.py", line 281, in <module>
    param = re_create(param[0], param[1], param[2], param[3])
  File "op.py", line 208, in re_create
    token_selenium = get_token_selenium()
  File "op.py", line 151, in get_token_selenium
    browser.find_element_by_xpath("/html/body/div[1]/div[3]/ul[3]/li[1]/a").click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 368, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 858, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[3]/ul[3]/li[1]/a"}
  (Session info: headless chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.9.10-040910-generic x86_64)

**Comment by aimkiray** [comment]
(๑•̀ω•́)ノ没注意到
循环加错了位置。。
