### ISSUE TITLE
这是什么意思？

### ISSUE THREAD

**Issue by hxf3591126** [aimkiray/op-script#5]
root@huang1024:~/op-script# python op.py
Traceback (most recent call last):
  File "op.py", line 41, in <module>
    browser = webdriver.Chrome(chrome_options=chrome_options)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 3.13.0-24-generic x86_64)

**Comment by aimkiray** [comment]
试试 Chrome 能否正常启动：
```bash
google-chrome --headless --disable-gpu --no-sandbox
```
不能的话重装试试（或者在 Windows 上操作，更简单）

**Comment by hxf3591126** [comment]
您的操作说明步骤都是ubuntu 的，windows 下，要怎么玩？

**Comment by aimkiray** [comment]
只是安装方法不同，去官网下载安装 Python3 和 Chrome，下载 chromedriver 添加到 Path，其他一样。

**Comment by hxf3591126** [comment]
有个说明就完美了。
git clone https://github.com/aimkiray/op-script.git

cd op-script

pip3 install -r requirements.txt

像这个东西，win上要怎么弄？

chromedriver 添加到 Path，这个是添加到什么路径呢？

**Comment by hxf3591126** [comment]
用win可以，谢谢

**Comment by hxf3591126** [comment]
[info] THE 1st attempt
[info] THE 2nd attempt

这样，是脚本在工作了吗

**Comment by aimkiray** [comment]
不客气！目测正常。。
