### ISSUE TITLE
The 1st attempt后报错

### ISSUE THREAD

**Issue by ly012** [aimkiray/op-script#6]
2017-12-22 18:58:03,460: [INFO]  The 1st attempt...
Traceback (most recent call last):
  File "op.py", line 296, in <module>
    create_loop("", "", get_local(), 1)
  File "op.py", line 210, in create_loop
    token_selenium = get_token_selenium()
  File "op.py", line 152, in get_token_selenium
    browser.find_element_by_xpath("/html/body/div[1]/div[3]/ul[3]/li[1]/a").click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 368, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 858, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[3]/ul[3]/li[1]/a"}
  (Session info: headless chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 2.6.32-042stab124.2 x86_64)

**Comment by aimkiray** [comment]
已修复，如果还不行的话试试 master 分支。
原因是食用指南的更新部分。
